### PR TITLE
Update GitHub Actions

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
The failing test is caused by #35.

**Comment by Hboni** [comment]
Thanks, @DimitriPapadopoulos, as our environment uses python3.6 for now, I wanted to keep 3.6 in Actions, so I fixed ubuntu-20.04 as a test environment. close #35

**Comment by DimitriPapadopoulos** [comment]
Rebased on `develop`.

I suggest you delete branch `master` if `develop` is used as the development branch.

**Comment by DimitriPapadopoulos** [comment]
The environment shouldn't use Python 3.6 as it is EOL'ed.

**Comment by Hboni** [comment]
`develop` is used as the development branch, but `master` is used as the deployment branch.

**Comment by DimitriPapadopoulos** [comment]
Ah, I get it. No version branches.

Python 3.6 is still needed for Ubuntu 18.04 as long as it is not EOL'ed itself, but virtual environments can move to Python 3.7 or newer.

**Pull request merged**
