### PR TITLE
Multiple private creator

### PR DESCRIPTION
**Pull request by Hboni**
Add the possibility to use several Private Creator values for the same private tag.
It allows config : 

| Tag | Name| Action | Private Creator |
| --- | --- | --- | --- |
| (2005, 0010) | Private Creator Tag | K | SIEMENS MR SDS 01 |
| (2005, 0010) | Private Creator Tag | K | SIEMENS MR SDI 02 |

### CODE REVIEW

**Review by rbregand — COMMENTED** [review]
Since good ! 
Don't you need to modify the function which return transforms the csv file into a dictionnary ? 
Are you sure the key won't be overwritten by the last value in the .csv ? Also you haven't change any .csv file to add a second value

**Comment by Hboni** [comment]
Modifications in config.py file are the modification of the function which return dict from csv file.
PrivateCreator value will not be overwritten, but the name and the action will be. As the name is not really used in deidentification it is not a real issue. But for the action maybe ... I can add a check to see if action is the same, but I am not sure what to do if it is not the case. I did not want to make a list of actions too. Do you think it will be necessary?

**Comment by rbregand** [comment]
It's possible that according to the value of a private change we want to do a specific action but since it's not the case actually may be it's not worth to change anything in this PR. 
But if we need it in the future may be a dictionary like this might help : 
```tags_profile[tag]= {value1 :{'name'=name1, 'action'=action1}, value2: {'name'=name, 'action'=action2}```

You can also put the name at a higher level in the dictionary. You know better than me if this solution is viable or not

**Review by rbregand — APPROVED** [review]

**Comment by Hboni** [comment]
The only issue that I see with your solution, is that the check mechanism is different between Public and Private Tags, But it may be more robust :+1:

**Pull request merged**
